on:
  push:

name: Build and test library
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: Install dependencies
        run: bun install

      - name: Build library
        run: bun run build

      - name: Run linter
        run: bun run lint

      - name: Check configuration
        run: bun run check:config
